defaults:
  - ogb_double_stack
  - _self_

world:
  max_episode_steps: 200

eval:
  protocol: full_task
  num_eval: 100
  num_contexts: 100
  stochastic_repeats: 1
  eval_budget: 200

output:
  filename: ogb_double_stack_full_results.txt
